sudo: required
language: generic
services: docker

script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  - docker build -t tectonic-fontawesome $TRAVIS_BUILD_DIR
  # Compiling only main.tex:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind tectonic-fontawesome /bin/sh -c "tectonic vadim.tex"